# re-export convenient bits for the main script
from .config import CFG, Config, \
    RUN_FILTER, RUN_MASK, RUN_INTERP_FILTER, RUN_NORM, RUN_TEMPLATES, \
    RUN_FEATURES_PROCRUSTES_GLOBAL, RUN_FEATURES_PROCRUSTES_PARTICIPANT, \
    RUN_FEATURES_ORIGINAL, RUN_LINEAR, SCALE_BY_INTEROCULAR, \
    SAVE_REDUCED, SAVE_MASKED, SAVE_INTERP_FILTERED, SAVE_NORM, \
    SAVE_PER_FRAME_PROCRUSTES_GLOBAL, SAVE_PER_FRAME_PROCRUSTES_PARTICIPANT, \
    SAVE_PER_FRAME_ORIGINAL, OVERWRITE, OVERWRITE_TEMPLATES, SCIPY_AVAILABLE
